### ISSUE TITLE
Why is this is ipld?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-cidutil#2]
Why is this is `ipld` and not `ipfs.  `go-cid` is in `ipfs`.  If we want this in `ipld` we should also move `go-cid` otherwise it is just confusing.

CC @Stebalien

**Comment by Stebalien** [comment]
I'm planning on moving *all* the IPLD stuff to the IPLD org. Unfortunately, doing so will break *everything* (thanks go!). So, my plan is to:

1. Fork everything (eventually).
2. Make any breaking interface changes we'd like.
3. Announce to the world "Use the `github.com/ipld/...` IPLD repos now!

If we just *move* the repos, github will try to do the smart thing and redirect but that'll just break everyone's code.

---

On the other hand... If we put this *here* and have it depend on `ipfs/go-cid`, we'll run into the same problem. Crap. I really wish go had a nice package repository system. I'll move it and we can try this again later.

**Comment by kevina** [comment]
Thanks.  Closing as I see that is done.
